# fly.toml app configuration file generated for travel-stream on 2025-02-25T10:44:48-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-stream'
primary_region = 'lax'
console_command = "/code/manage.py shell"

[build]

[env]
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"
